language: node_js
dist: trusty
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
addons:
  chrome: stable
install:
  - wget -O yarn.tar.gz https://yarnpkg.com/latest.tar.gz
  - tar zvxf yarn.tar.gz
  - export PATH=`pwd`/dist/bin:$PATH
  - cd frontend
  - yarn install
script:
  - yarn run test -- --progress=false --watch=false --browsers=ChromeHeadlessNoSandbox
  - yarn run build-prod
